dark = true
syntax_theme = "base16-eighties.dark"

background = "#272822"
panel = "#2e2f2a"
panel_alt = "#383932"
panel_light = "#49483e"
text = "#f8f8f2"
muted = "#75715e"
border = "#49483e"
accent = "#a6e22e"
accent_soft = "#66d9ef"
success = "#a6e22e"
warning = "#e6db74"
error = "#f92672"
diff_add = "#9bcd97"
diff_delete = "#fc533a"
diff_add_bg = "#30503c"
diff_delete_bg = "#64322a"
selection_bg = "#a6e22e"
selection_fg = "#ffffff"
mode_build = "#a6e22e"
mode_plan = "#75715e"
