dark = true
syntax_theme = "base16-mocha.dark"

background = "#282a36"
panel = "#313244"
panel_alt = "#363848"
panel_light = "#44475a"
text = "#f8f8f2"
muted = "#6272a4"
border = "#44475a"
accent = "#bd93f9"
accent_soft = "#9580ff"
success = "#50fa7b"
warning = "#f1fa8c"
error = "#ff5555"
diff_add = "#9bcd97"
diff_delete = "#fc533a"
selection_bg = "#bd93f9"
selection_fg = "#ffffff"
mode_build = "#50fa7b"
mode_plan = "#6272a4"
