dark = true
syntax_theme = "base16-eighties.dark"

background = "#2d352c"
panel = "#374136"
panel_alt = "#404a3f"
panel_light = "#4d584c"
text = "#d3c6aa"
muted = "#6c7963"
border = "#485446"
accent = "#83a568"
accent_soft = "#648250"
success = "#83a568"
warning = "#d6ae55"
error = "#e67e6e"
diff_add = "#9bcd97"
diff_delete = "#fc533a"
selection_bg = "#83a568"
selection_fg = "#ffffff"
mode_build = "#83a568"
mode_plan = "#6c7963"
