dark = true
syntax_theme = "base16-eighties.dark"

background = "#282828"
panel = "#32302f"
panel_alt = "#3c3836"
panel_light = "#504945"
text = "#ebdbb2"
muted = "#a89884"
border = "#504945"
accent = "#fabd2f"
accent_soft = "#d79921"
success = "#b8bb26"
warning = "#fe8019"
error = "#fb4934"
diff_add = "#9bcd97"
diff_delete = "#fc533a"
diff_add_bg = "#30503c"
diff_delete_bg = "#64322a"
selection_bg = "#fabd2f"
selection_fg = "#ffffff"
mode_build = "#83a598"
mode_plan = "#a89884"
