dark = true
syntax_theme = "base16-mocha.dark"

background = "#1a202c"
panel = "#272e3e"
panel_alt = "#31394c"
panel_light = "#414b5f"
text = "#dfe2f7"
muted = "#aab6d3"
border = "#434a65"
accent = "#9f93ff"
accent_soft = "#786dba"
success = "#a2be8c"
warning = "#efb866"
error = "#f17c97"
diff_add = "#9bcd97"
diff_delete = "#fc533a"
diff_add_bg = "#30503c"
diff_delete_bg = "#64322a"
selection_bg = "#9f93ff"
selection_fg = "#ffffff"
mode_build = "#9f93ff"
mode_plan = "#786dba"
