dark = true
syntax_theme = "base16-ocean.dark"

background = "#2e3440"
panel = "#3b4252"
panel_alt = "#434c5e"
panel_light = "#505a6e"
text = "#e5e9f0"
muted = "#88c0d0"
border = "#515d6a"
accent = "#a3be8c"
accent_soft = "#74919f"
success = "#a3be8c"
warning = "#e88191"
error = "#bf616a"
diff_add = "#9bcd97"
diff_delete = "#fc533a"
diff_add_bg = "#30503c"
diff_delete_bg = "#64322a"
selection_bg = "#a3be8c"
selection_fg = "#ffffff"
mode_build = "#a3be8c"
mode_plan = "#74919f"
