dark = true
syntax_theme = "base16-ocean.dark"

background = "#282c34"
panel = "#303440"
panel_alt = "#3c404c"
panel_light = "#4b505f"
text = "#abb2bf"
muted = "#6272a4"
border = "#4c566a"
accent = "#61afef"
accent_soft = "#7881af"
success = "#98c379"
warning = "#e06c75"
error = "#e74c3c"
diff_add = "#9bcd97"
diff_delete = "#fc533a"
diff_add_bg = "#30503c"
diff_delete_bg = "#64322a"
selection_bg = "#61afef"
selection_fg = "#ffffff"
mode_build = "#61afef"
mode_plan = "#7881af"
