dark = true
syntax_theme = "base16-ocean.dark"

background = "#191724"
panel = "#1f1d2e"
panel_alt = "#26233a"
panel_light = "#312f44"
text = "#e0def4"
muted = "#908caa"
border = "#26233a"
accent = "#eb6f92"
accent_soft = "#c4a7e7"
success = "#9ccfd8"
warning = "#f6c177"
error = "#eb6f92"
diff_add = "#9bcd97"
diff_delete = "#fc533a"
selection_bg = "#eb6f92"
selection_fg = "#ffffff"
mode_build = "#eb6f92"
mode_plan = "#908caa"
