dark = false
syntax_theme = "InspiredGitHub"

background = "#fffaf4"
panel = "#fcf6ef"
panel_alt = "#f5efea"
panel_light = "#f8f2ee"
text = "#575279"
muted = "#827d96"
border = "#d7cdc4"
accent = "#eb6f92"
accent_soft = "#f093c7"
success = "#286983"
warning = "#ea9d34"
error = "#eb6f92"
diff_add = "#3a8437"
diff_delete = "#ed4831"
selection_bg = "#eb6f92"
selection_fg = "#ffffff"
mode_build = "#eb6f92"
mode_plan = "#9893a5"
