dark = true
syntax_theme = "Solarized (dark)"

background = "#002b36"
panel = "#073642"
panel_alt = "#143e4a"
panel_light = "#234854"
text = "#839496"
muted = "#93a1a1"
border = "#268bd2"
accent = "#268bd2"
accent_soft = "#586e75"
success = "#2aa198"
warning = "#cb4b16"
error = "#dc322f"
diff_add = "#9bcd97"
diff_delete = "#fc533a"
diff_add_bg = "#30503c"
diff_delete_bg = "#64322a"
selection_bg = "#268bd2"
selection_fg = "#ffffff"
mode_build = "#268bd2"
mode_plan = "#586e75"
