use axum::{
    body::Body,
    http::{StatusCode, Uri, header, HeaderValue},
    response::{IntoResponse, Response},
};

// Generated by build.rs — uses include_bytes! for each file in OUT_DIR/web-dist/
include!(concat!(env!("OUT_DIR"), "/web_assets_generated.rs"));

/// Determine Cache-Control header based on file path.
///
/// Vite places all content-hashed assets (JS, CSS, fonts, images) under the
/// `/assets/` directory — their filenames change when content changes, so
/// they can be cached permanently (`immutable`).  `index.html` is the SPA
/// entry point and must always be validated.  Everything else gets a
/// moderate cache duration.
fn cache_control_for_path(path: &str) -> &'static str {
    if path.starts_with("assets/") {
        // Content-hashed asset — filename changes when content does
        "public, max-age=31536000, immutable"
    } else if path == "index.html" {
        // SPA shell — always check for a fresh version
        "public, no-cache"
    } else {
        // favicon, icons, etc.
        "public, max-age=86400"
    }
}

/// Serve an embedded file by path
pub fn serve_file(path: &str) -> Option<Response> {
    let asset = get_asset_internal(path)?;

    let mime = mime_guess::from_path(path).first_or_octet_stream();
    let cache_control = cache_control_for_path(path);

    let response = Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, mime.as_ref())
        .header(header::CACHE_CONTROL, HeaderValue::from_static(cache_control))
        .body(Body::from(asset))
        .ok()?;

    Some(response)
}

/// Handle a request for an embedded asset
pub async fn handle_embedded_request(uri: Uri) -> impl IntoResponse {
    let path = uri.path().trim_start_matches('/');

    // Try to serve the exact path
    if let Some(response) = serve_file(path) {
        return response;
    }

    // If path is empty or directory-like, try index.html
    if (path.is_empty() || path.ends_with('/'))
        && let Some(response) = serve_file(&format!("{}index.html", path))
    {
        return response;
    }

    // Try appending .html for SPA routes
    if !path.contains('.')
        && let Some(response) = serve_file(&format!("{}.html", path))
    {
        return response;
    }

    // Fallback to index.html for SPA routing (client-side routing)
    if let Some(response) = serve_file("index.html") {
        return response;
    }

    // Last resort: 404
    (StatusCode::NOT_FOUND, "Not found").into_response()
}

/// Check if embedded assets are available
pub fn has_embedded_assets() -> bool {
    has_assets_internal()
}

/// List available embedded assets (for debugging)
#[allow(dead_code)]
pub fn list_assets() -> Vec<String> {
    ASSET_PATHS.iter().map(|s| s.to_string()).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_embedded_assets_available() {
        // This test verifies that the embedding worked
        if has_embedded_assets() {
            let assets = list_assets();
            assert!(!assets.is_empty(), "Embedded assets should not be empty");
            eprintln!("Embedded assets: {:?}", assets);
        }
    }
}
