[package]
name = "tidev-search"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "tidev workspace file search utilities"

[lib]
name = "tidev_search"

[dependencies]
anyhow = "1.0.102"
ignore = "0.4.26"
grep = "0.4.1"
log = "0.4.32"
notify = "8.2.0"
rayon = "1.12.0"
serde = { version = "1.0.228", features = ["derive", "rc"] }
tidev-types = { path = "../tidev-types" }
